apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-app-deployment
  labels:
    app: app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 3000
        resources:
        #guarnteed resources
          requests:
            memory: "512Mi"
            cpu: "100m"
        #maximum resources
          limits:
            memory: "1024Mi"
            cpu: "200m"
#usually containers only use 30% of requested CPU 
#EKS Cost Monitoring Plugins: kube-resource-report or Kubecost


